### ISSUE TITLE
.json() maximum size/length?

### ISSUE THREAD

**Issue by xmflsct** [sindresorhus/ky-universal#15] opened 2020-04-11 20:15 UTC
I recently encounter a very strange situation. My `ky.get().json()` hangs without any response.

The project sends API query to [Contentful](https://www.contentful.com/) and gets response. I tried multiple times and finally figure out that, there seems to be limit of the response size/length?

In Postman, I can see that my limit is around 3.3 KB. Any of you encounter similar situation?

**Comment by sholladay** [comment] 2020-04-12 19:04
Duplicate of #8

**Closed by sholladay** 2020-04-12 19:04 UTC

**Comment by sholladay** [comment] 2020-04-12 19:16
Pretty sure this is a `node-fetch` bug related to how it uses streams. See discussion and linked issues in #8 for details.

I provided a workaround in https://github.com/sindresorhus/ky-universal/issues/8#issuecomment-509789901 that you may want to look at. If you use it, please let me know if it solves the problem for you.
