### ISSUE TITLE
afterResponse hook stops response from resolving

### ISSUE THREAD

**Issue by paambaati** [sindresorhus/ky-universal#18] opened 2020-05-04 07:19 UTC
Repro — https://github.com/paambaati/ky-body-timeout-repro

I use `ky` and `ky-universal` in a Next.js app and I noticed responses failing with a `body-timeout` error on the Node.js side only for responses above roughly 50KB in size. I've tried tweaking the `highWatermark` and `size` options, but it doesn't seem to have an effect.

I have an `afterResponse` hook that does some additional stuff like logging the responses, redirecting to my login page if the response is a `401`, etc.

If I remove the hook, it works. This is illustrated in my repro where I've added a hook with just one `console.log` statement, and you can see the issue occurring. Returning the `res` has no effect. If the hook is completely removed on the repro, it works.

CC: @sindresorhus, @sholladay, @szmarczak

**Comment by sholladay** [comment] 2020-05-04 18:01
Duplicate of https://github.com/sindresorhus/ky-universal/issues/8

**Comment by sholladay** [comment] 2020-05-04 18:23
Yes, this is a known bug (see the linked issue above). The problem is that when you use an `afterResponse` hook, we [clone the response](https://github.com/sindresorhus/ky/blob/e4e820c4ba94651a795a4e23f79e4bdc4afd10c1/index.js#L280) and `node-fetch` has a bug in its `clone()` implementation that can cause the promise to never resolve when the response body is large. I detailed a temporary workaround [here](https://github.com/sindresorhus/ky-universal/issues/8#issuecomment-509789901).

I see that you tried to use `highWaterMark` as a workaround (which the `node-fetch ` team mentioned [here](https://github.com/sindresorhus/ky-universal/issues/8#issuecomment-534705671)), but that won't work at the moment because `ky-universal` currently depends on `node-fetch` version 2, which does not support setting `highWaterMark` manually. I just checked npm and I see that there _is_ a beta release for `node-fetch` version 3 available, which should support the `highWaterMark` option.

I don't know if Sindre would be comfortable using the beta in a stable release of `ky-universal`, but we can at least open a PR to get the ball rolling and people can use the git branch if need be.

**Closed by sholladay** 2020-05-04 18:23 UTC

**Comment by sindresorhus** [comment] 2020-05-04 18:50
I'm willing to target the beta.

**Comment by paambaati** [comment] 2020-05-05 03:51
@sholladay @sindresorhus Thanks, and FWIW, the v3 beta of node-fetch is almost ready, as most of the items on their [v3 roadmap](https://github.com/node-fetch/node-fetch/issues/668) are done.

**Comment by paambaati** [comment] 2020-05-05 04:01
@sholladay Also, in the example repro, you’ll notice that the suggested workaround doesn’t work — see https://github.com/paambaati/ky-body-timeout-repro/blob/master/index.js

I am, in fact, calling `.method()` and `.json()` in separate lines without chaining.

Do you have any other suggestions to make this work for now? I’ve invested a fair bit of time and effort in setting up my API layer (middleware for logging, headers/cookie management, redirection & error handlers, etc.) based on `ky-universal` and it would be very time-consuming to change it all if this issue’s a blocker.

**Comment by sholladay** [comment] 2020-05-05 06:40
You need to avoid using the three features I mentioned in the linked issue. Each of those features clone the response, which triggers the bug. Using body method shorthands is only one of the relevant features, so using the verbose syntax won't fix your code on it's own, as you are still using an `afterResponse` hook.

Needless to say, it's a major issue, hence the bounty attached to it.

If you cannot modify your code to avoid using those features, then my recommendation is to fork Ky and update the `node-fetch` dependency in package.json to use the v3 beta. If you end up doing that, feel free to submit a PR. Otherwise, I'll take care of it myself within the next few days.
