### ISSUE TITLE
Must use import to load ES Module

### ISSUE THREAD

**Issue by matveychuk** [sindresorhus/ky-universal#31] opened 2021-01-17 10:23 UTC
When trying to use ky/ky-universal with the newly created Next.js app receive such error:
Error: Must use import to load ES Module: /Users/---/node_modules/ky-universal/index.js
require() of ES modules is not supported.
require() of /---/node_modules/ky-universal/index.js from /---/.next/server/pages/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /---/node_modules/ky-universal/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /---/node_modules/ky-universal/package.json.

Packages version:
Node 14.15.4,
"dependencies": {
    "ky": "^0.26.0",
    "ky-universal": "^0.9.1",
    "next": "10.0.5",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }
  
  Code extract
```
import ky from "ky-universal";

export default function Home() {
  const fetchData = async () => {
    const res = await ky
      .get("https://jsonplaceholder.typicode.com/todos/1")
      .json();
    setData(res);
    console.log(res);
  };
```

**Comment by sindresorhus** [comment] 2021-01-17 10:59
Duplicate of https://github.com/sindresorhus/ky-universal/issues/30

**Comment by sindresorhus** [comment] 2021-01-17 11:00
I would open an issue over at https://github.com/vercel/next.js This package is correctly set up for ESM, so Next.js is doing something wrong.

**Closed by sindresorhus** 2021-01-17 10:59 UTC
